// Use .apex files to store anonymous Apex.
// You can execute anonymous Apex in VS Code by selecting the
//     apex text and running the command:
//     SFDX: Execute Anonymous Apex with Currently Selected Text
// You can also execute the entire file by running the command:
//     SFDX: Execute Anonymous Apex with Editor Contents
//GB-2313_FileName
////GB-2313_1_testlog
string tempvar = 'GB-2313_1';
System.debug('Scripts for GB-2313_1');
System.debug('Anonymus Scripts for @@@@ ' + tempvar);

