name: Manual Step Automation

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  manualStepAutomation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check PR merge status
        id: pr_merge_status
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_MERGE_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | jq -r '.merged')
          echo "PR Merge Status: $PR_MERGE_STATUS"
          merge_status="$PR_MERGE_STATUS"
          echo "merge_status=$merge_status" >> $GITHUB_OUTPUT

      - name: Get Changes From PR
        id: list-files
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files"
          CHANGED_FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $API_URL | jq -r '.[].filename')

          # Convert the list to a newline-delimited string
          CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')
          
          echo "Files with changes in PR #${PR_NUMBER}:"
          echo "$CHANGED_FILES"
          changed_files="${CHANGED_FILES}"
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT

      - name: Get Source Branch Name
        id: source-branch
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          SOURCE_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | jq -r '.base.ref')
          echo "Source Branch: $SOURCE_BRANCH"
          echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT

      - name: Set up Python
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Cache Python dependencies
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Python dependencies
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run Python script
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        run: |
          python main.py ${{ steps.list-files.outputs.changed_files }} ${{ steps.source-branch.outputs.source_branch }}

      - name: Configure Git with PAT
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        run: |
          git config --global user.email "${{ vars.USER_EMAIL }}"
          git config --global user.name "${{vars.USER_NAME }}"
        env:
          PAT: ${{ secrets.REPO_PAT_SECRET }}
    
      - name: Check for Results folder
        if: steps.pr_merge_status.outputs.merge_status == 'true'
        id: Folder_check
        run: |
          if [ -d "Results/" ]; then
            var="true"
            echo "Folder_found=$var" >> $GITHUB_OUTPUT
          else
            var="false"
            echo "Folder_found=$var" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.pr_merge_status.outputs.merge_status == 'true' && steps.Folder_check.outputs.Folder_found == 'true'
        run: |
          releaseName="Results/"
          if git status --porcelain "$releaseName" | grep .; then
            git add "$releaseName"
            git commit -m "Add Manual Step Automation Script generated folder for $releaseName"
            git push
          else
            echo "No changes to commit, working tree clean."
            fi

      - name: Skip workflow on PR not merged
        if: steps.pr_merge_status.outputs.merge_status == 'false'
        run: |
          echo "This workflow was skipped because the PR was not merged."
