name: Check Commit Messages

on:
  push:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Commit Message
        id: latest_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Check for "alpha" in Commit Message
        id: alpha_check
        run: |
          specific_word="alpha" 
          latest_commit_message="${{ steps.latest_commit.outputs.message }}"
          echo "Commit Message '$latest_commit_message' "
          
          if [[ $latest_commit_message == *"$specific_word"* ]]; then
            echo "Found the specific word '$specific_word' in the latest commit message."
            var="true"
            echo "::set-output name=alpha_found::$var"
            
            # Split the commit message into words
            IFS=' ' read -ra commit_message_words <<< "$latest_commit_message"
            
            # Store the second and third words in environment variables if they exist
            if [[ ${#commit_message_words[@]} -ge 3 ]]; then
              second_word="${commit_message_words[1]}"
              third_word="${commit_message_words[2]}"
              echo "::set-output name=second_word::$second_word"
              echo "::set-output name=third_word::$third_word"
            fi
          else
            echo "The specific word '$specific_word' was not found in the latest commit message."
            var="true"
            echo "::set-output name=alpha_found::$var"
          fi

      - name: Print 2nd and 3rd Words
        if: steps.alpha_check.outputs.alpha_found == 'true'
        run: |
          echo "Second Word: '${{ steps.alpha_check.outputs.second_word }}'"
          echo "Third Word: '${{ steps.alpha_check.outputs.third_word }}'"

      - name: Set up Python
        if: steps.alpha_check.outputs.alpha_found == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Python dependencies
        if: steps.alpha_check.outputs.alpha_found == 'true'
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Python dependencies
        if: steps.alpha_check.outputs.alpha_found == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run Python script
        if: steps.alpha_check.outputs.alpha_found == 'true'
        run: |
          python mainGA.py "${{ steps.alpha_check.outputs.second_word }}" "{{ steps.alpha_check.outputs.third_word }}" "Y"

      - name: Configure Git with PAT
        if: steps.alpha_check.outputs.alpha_found == 'true'
        run: |
          git config --global user.email "amit.kumar@fexle.com"
          git config --global user.name "Amit-Fexle-Training"
        env:
          PAT: ${{ secrets.REPO_PAT_SECRET }}
    
      - name: Commit and push changes
        if: steps.alpha_check.outputs.alpha_found == 'true'
        run: |
          releaseName="${{ github.event.inputs.input1 }}_results/"
          git add "$releaseName"  # Useing the releaseName as part of the path
          git commit -m "Add Manual Step Automation Script generated folder for $releaseName"
          git push
