name: Check Commit Messages

on:
  push:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Commit Messages
        run: |
          specific_word="alpha"  # Replace with the word you want to check
          if [[ $latest_commit_message == *"$specific_word"* ]]; then
            echo "Found the specific word '$specific_word' in the latest commit message."
          else
            echo "The specific word '$specific_word' was not found in the latest commit message."
            # You can add additional actions or notifications here.
          fi
