name: Extract Orgname and Release

on:
  push:
    branches:
      - main

jobs:
  extract-orgname-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Commit Message
        id: latest_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Set Boolean Variable if "alpha" is present
        id: set_boolean
        run: |
          specific_word="alpha"
          latest_commit_message="${{ steps.latest_commit.outputs.message }}"
          if [[ $latest_commit_message == *"$specific_word"* ]]; then
            echo "::set-output name=found_alpha::true"
          else
            echo "::set-output name=found_alpha::false"
          fi

      - name: Extract Orgname and Release
        if: steps.set_boolean.outputs.found_alpha == 'true'
        id: extract_data
        run: |
          latest_commit_message="${{ steps.latest_commit.outputs.message }}"
          # Extract Orgname and Release using regular expressions
          if [[ $latest_commit_message =~ ([A-Za-z]+) ([A-Za-z0-9]+) ]]; then
            orgname="${BASH_REMATCH[1]}"
            release="${BASH_REMATCH[2]}"
            echo "Orgname: $orgname"
            echo "Release: $release"
          fi
