name: Check Commit Messages

on:
  push:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Commit Message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Check Commit Messages
        id: alpha_check
        run: |
          specific_word="alpha" 
          latest_commit_message="${{ steps.latest_commit.outputs.message }}"
          echo "Commit Message '$latest_commit_message' "
          
          if [[ $latest_commit_message == *"$specific_word"* ]]; then
            echo "Found the specific word '$specific_word' in the latest commit message."
            echo "##vso[task.setvariable variable=alpha_found]true"
            
            # Split the commit message into words
            IFS=' ' read -ra commit_message_words <<< "$latest_commit_message"
            
            # Store the second and third words in environment variables if they exist
            if [[ ${#commit_message_words[@]} -ge 3 ]]; then
              export SECOND_WORD="${commit_message_words[1]}"
              export THIRD_WORD="${commit_message_words[2]}"
            fi
          else
            echo "The specific word '$specific_word' was not found in the latest commit message."
            echo "##vso[task.setvariable variable=alpha_found]false"
          fi

      - name: Print 2nd and 3rd Words
        if: env.alpha_found == 'true'
        run: |
          echo "Second Word: '$SECOND_WORD'"
          echo "Third Word: '$THIRD_WORD'"
