name: Check Commit Messages

on:
  push:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Commit Messages
        run: |
          specific_word="alpha"  # Replace with the word you want to check
          found=false

          # Iterate through the commit messages
          for commit_message in $(git log --format=%s); do
            if [[ $commit_message == *"$specific_word"* ]]; then
              echo "Found the specific word '$specific_word' in one of the commit messages."
              found=true
              break
            fi
          done

          if [[ "$found" == "false" ]]; then
            echo "The specific word '$specific_word' was not found in the commit messages."
            # You can add additional actions or notifications here.
          fi
