name: Check Commit Messages

on:
  push:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Commit Message
        id: latest_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Check Commit Messages
        run: |
          specific_word="beta1"  # Replace with the word you want to check
          latest_commit_message="${{ steps.latest_commit.outputs.message }}"
          echo "Commit Message '$latest_commit_message' "
          if [[ $latest_commit_message == *"$specific_word"* ]]; then
            echo "Found the specific word '$specific_word' in the latest commit message."
          else
            echo "The specific word '$specific_word' was not found in the latest commit message."
            # You can add additional actions or notifications here.
          fi
          
