name: Manual Step Automation

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Please Enter The Release Name'
        required: true
        type: string
      input2:
        description: |
                      Select The Org :
                      1. Prod
                      2. Twgqa2d
        required: true
        type: choice
        options:
          - '1'
          - '2'
      input3:
        description: 'Confirm your choice (Y/N)'
        required: true
        default: 'Y'
        type: choice
        options:
          - Y
          - N
jobs:
  manualStepAutomation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run Python script
        run: |
          python mainGA.py "${{inputs.input1}}" "${{inputs.input2}}" "${{inputs.input3}}"

      - name: Configure Git with PAT
        run: |
          git config --global user.email "amit.kumar@fexle.com"
          git config --global user.name "Amit-Fexle-Training"
        env:
          PAT: ${{ secrets.REPO_PAT_SECRET }}
    
      - name: Commit and push changes
        run: |
          releaseName="${{ github.event.inputs.input1 }}_results/"
          git add "$releaseName"  # Useing the releaseName as part of the path
          git commit -m "Add Manual Step Automation Script generated folder for $releaseName"
          git push
    
