name: Get Changed File From PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
   changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: List Files with Changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.sha }})
          echo "Files with changes in PR #${{ github.event.pull_request.number }}:"
          echo "$CHANGED_FILES"
